# Generated by Django 3.2 on 2021-05-30 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0004_auto_20210530_0432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='guides',
        ),
        migrations.AddField(
            model_name='destination',
            name='guides',
            field=models.ManyToManyField(to='travello.Guide'),
        ),
    ]
