# Generated by Django 3.2 on 2021-05-31 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0008_auto_20210530_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='end_time',
            field=models.DateTimeField(default='2000-1-1 1:00'),
        ),
        migrations.AddField(
            model_name='destination',
            name='start_time',
            field=models.DateTimeField(default='2000-1-1 1:00'),
        ),
        migrations.AddField(
            model_name='guide',
            name='time_end',
            field=models.DateTimeField(default='2000-1-1 1:00'),
        ),
        migrations.AddField(
            model_name='guide',
            name='time_start',
            field=models.DateTimeField(default='2000-1-1 1:00'),
        ),
    ]
