# Generated by Django 3.2 on 2021-05-31 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0006_auto_20210530_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='end_time',
        ),
    ]
