# Generated by Django 3.2 on 2021-05-31 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0007_remove_destination_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='guide',
            name='time_end',
        ),
        migrations.RemoveField(
            model_name='guide',
            name='time_start',
        ),
    ]
